debug: false
logging:
  level:
    root: WARN
    org:
      springframework:
        ai:
          chat:
            client:
              advisor: WARN

spring:
  ai:
    chat:
      client:
        observations:
          include-input: false

  data:
    mongodb:
      host: localhost
      port: 27018
      database: interview
      username: mongouser
      password: mongopw
